### PR TITLE
Experiment api activities

### PR DESCRIPTION
**Pull request by ViniSCode**
Html, CSS and Javascript

### CODE REVIEW

**Comment by viniRdev** [comment]
Lembrar de fazer responsivo

**Comment by viniRdev** [comment]
Responsive Layout

**Comment by ViniSCode** [comment]
Responsive Layout

**Review by viniRdev — COMMENTED** [review]
Make it responsive

**Comment by ViniSCode** [comment]
Mudar CSS

**Review by viniRdev — COMMENTED** [review]
responsive

**Review by viniRdev — APPROVED** [review]
LGTM 👍

**Pull request merged**
